# Week 8: Building Blocks

## Matrices

Consider the model  
$y = Xb + e$  

where 

$ y = 
        \begin{pmatrix}
        15.1 \\
        07.9 \\
        04.5 \\
        12.8 \\
        10.5 \\
        \end{pmatrix} 
\quad X = 
        \begin{pmatrix}
        1 & 25.5 & 1.23 \\
        1 & 40.8 & 1.89 \\
        1 & 30.2 & 1.55 \\
        1 & 04.3 & 1.18 \\
        1 & 10.7 & 1.68 \\
        \end{pmatrix}
$  


and $b$ a _3 × 1_ vector, and $e$ a _5 × 1_ vector. 

***QUESTION 1***  

Calculate the values of the vector $e$ for:

**Case 1:**  

$$ b = 
        \begin{pmatrix}
        23.0 \\
        00.10 \\
        −8.00 \\
        \end{pmatrix} 
$$  


**Case 2:**  

$$ b = 
        \begin{pmatrix}
        22.0 \\
        −0.20 \\
        −7.00 \\
        \end{pmatrix} 
$$

In [1]:
import numpy as np

In [2]:
# defining the vector y
y = np.array([
    [15.1],
    [7.9],
    [4.5],
    [12.8],
    [10.5]
])
y

array([[ 15.1],
       [  7.9],
       [  4.5],
       [ 12.8],
       [ 10.5]])

In [3]:
# defining the matrix X
X = np.matrix([
    [1, 25.5, 1.23],
    [1, 40.8, 1.89],
    [1, 30.2, 1.55],
    [1, 04.3, 1.18],
    [1, 10.7, 1.68]
])
X

matrix([[  1.  ,  25.5 ,   1.23],
        [  1.  ,  40.8 ,   1.89],
        [  1.  ,  30.2 ,   1.55],
        [  1.  ,   4.3 ,   1.18],
        [  1.  ,  10.7 ,   1.68]])

In [4]:
# b as defined in case 1
b = np.array([
    [23.0],
    [0.10],
    [-8.0]
])
b

array([[ 23. ],
       [  0.1],
       [ -8. ]])

In [5]:
e1 = y - (np.dot(X,b))
e1

matrix([[-0.61],
        [-4.06],
        [-9.12],
        [-1.19],
        [-0.13]])

In [6]:
# b as defined in case 2
b = np.array([
    [22.0],
    [-0.20],
    [-7.0]
])
b

array([[ 22. ],
       [ -0.2],
       [ -7. ]])

In [7]:
e2 = y - (np.dot(X,b))
e2

matrix([[ 6.81],
        [ 7.29],
        [-0.61],
        [-0.08],
        [ 2.4 ]])

***QUESTION 2***

The vector $e$ contains the unexplained part of the model. We like the unexplained part to be small, with which we mean that each element of the vector $e$ is close to zero. You can measure the distance of an element to zero by its absolute value, or by its square. Which of the two candidates for the vector $b$ gives the smallest unexplained part for the two distance measures?

In [8]:
# sum of absolute elements
print("Absolute Error on b from Case 1", np.absolute(e1).sum())
print("Absolute Error on b from Case 2", np.absolute(e2).sum())

Absolute Error on b from Case 1 15.11
Absolute Error on b from Case 2 17.19


In [9]:
# sum of square of elements
print("Square Error on b from Case 1", np.square(e1).sum())
print("Square Error on b from Case 2", np.square(e2).sum())

Square Error on b from Case 1 101.4631
Square Error on b from Case 2 105.6587


***QUESTION 3***

Let $A$ be a $(p × q)$ matrix, $u$ a $(1 × p)$ vector, and $v$ a $(q × 1)$ vector. What dimensions does $d = u·A·v$ have? 

Write the result in sigma notation (i.e., with P).

$$(1 × p)\quad X\quad(p × q)\quad X\quad(q × 1)$$
=
$$(1 × q)\quad X\quad(q × 1)$$
= $$(1 × 1)$$


***QUESTION 3***

Find a simplified expression without parentheses for $(A+I)^2$ , with $A$ a $(p × p)$ matrix, and $I$ the $(p × p)$ identity matrix.