# Week 8: Building Blocks

## Matrices

### Exercise 1

Consider the model  
$y = Xb + e$  

where 

$ y = 
        \begin{pmatrix}
        15.1 \\
        07.9 \\
        04.5 \\
        12.8 \\
        10.5 \\
        \end{pmatrix} 
\quad X = 
        \begin{pmatrix}
        1 & 25.5 & 1.23 \\
        1 & 40.8 & 1.89 \\
        1 & 30.2 & 1.55 \\
        1 & 04.3 & 1.18 \\
        1 & 10.7 & 1.68 \\
        \end{pmatrix}
$  


and $b$ a _3 × 1_ vector, and $e$ a _5 × 1_ vector. 

***QUESTION 1***  

Calculate the values of the vector $e$ for:

**Case 1:**  

$$ b = 
        \begin{pmatrix}
        23.0 \\
        00.10 \\
        -8.00 \\
        \end{pmatrix} 
$$  


**Case 2:**  

$$ b = 
        \begin{pmatrix}
        22.0 \\
        -0.20 \\
        -7.00 \\
        \end{pmatrix} 
$$

In [1]:
import numpy as np

In [2]:
# defining the vector y
y = np.array([
    [15.1],
    [7.9],
    [4.5],
    [12.8],
    [10.5]
])
y

array([[ 15.1],
       [  7.9],
       [  4.5],
       [ 12.8],
       [ 10.5]])

In [3]:
# defining the matrix X
X = np.matrix([
    [1, 25.5, 1.23],
    [1, 40.8, 1.89],
    [1, 30.2, 1.55],
    [1, 04.3, 1.18],
    [1, 10.7, 1.68]
])
X

matrix([[  1.  ,  25.5 ,   1.23],
        [  1.  ,  40.8 ,   1.89],
        [  1.  ,  30.2 ,   1.55],
        [  1.  ,   4.3 ,   1.18],
        [  1.  ,  10.7 ,   1.68]])

In [4]:
# b as defined in case 1
b = np.array([
    [23.0],
    [0.10],
    [-8.0]
])
b

array([[ 23. ],
       [  0.1],
       [ -8. ]])

In [5]:
e1 = y - (np.dot(X,b))
e1

matrix([[-0.61],
        [-4.06],
        [-9.12],
        [-1.19],
        [-0.13]])

In [6]:
# b as defined in case 2
b = np.array([
    [22.0],
    [-0.20],
    [-7.0]
])
b

array([[ 22. ],
       [ -0.2],
       [ -7. ]])

In [7]:
e2 = y - (np.dot(X,b))
e2

matrix([[ 6.81],
        [ 7.29],
        [-0.61],
        [-0.08],
        [ 2.4 ]])

***QUESTION 2***

The vector $e$ contains the unexplained part of the model. We like the unexplained part to be small, with which we mean that each element of the vector $e$ is close to zero. You can measure the distance of an element to zero by its absolute value, or by its square. Which of the two candidates for the vector $b$ gives the smallest unexplained part for the two distance measures?

In [8]:
# sum of absolute elements
print("Absolute Error on b from Case 1", np.absolute(e1).sum())
print("Absolute Error on b from Case 2", np.absolute(e2).sum())

Absolute Error on b from Case 1 15.11
Absolute Error on b from Case 2 17.19


In [9]:
# sum of square of elements
print("Square Error on b from Case 1", np.square(e1).sum())
print("Square Error on b from Case 2", np.square(e2).sum())

Square Error on b from Case 1 101.4631
Square Error on b from Case 2 105.6587


***QUESTION 3***

Let $A$ be a $(p X q)$ matrix, $u$ a $(1 X p)$ vector, and $v$ a $(q X 1)$ vector. What dimensions does $d = u·A·v$ have? 

Write the result in sigma notation (i.e., with P).

***ANSWER 3***

$$(1 X p)\quad X\quad(p X q)\quad X\quad(q X 1)$$
=
$$(1 X q)\quad X\quad(q X 1)$$
= $$(1 X 1)$$


Matrix multiplication of $u$ and $A$ can be written as $\sum_{i=1}^{p}\sum_{j=1}^{q}{u_i.A_{ij}.v_j}$ 

***QUESTION 4***

Find a simplified expression without parentheses for $(A+I)^2$ , with $A$ a $(p X p)$ matrix, and $I$ the $(p X p)$ identity matrix.

***ANSWER 4***  

The expansion of the term $(A+I)^2$ is $A^2 + AI + IA + I^2$

Since $I$ is an identity matrix, $A.I = I.A = A$  

So the overall expression can be written as $A^2 + 2A + I$

### Exercise 2

***QUESTION 1***

Let $a$ and $b$ be two $(p x 1)$ vectors. Multiply out the parentheses and simplify ${(a + b)}^\intercal.(a + b)$.

***ANSWER***  

$ = a.a^\intercal + a^\intercal.b + b^\intercal.a + b.b^\intercal$  
$ = a.a^\intercal + 2a^\intercal.b + b.b^\intercal$

hence $b^\intercal.a  = a^\intercal.b$ where $b^\intercal.a$ is scalar

In [30]:
# Example:

a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

a_transpose = a.transpose()
b_transpose = b.transpose()

In [32]:
print(np.dot(a_transpose, b))
print(np.dot(b_transpose, a))

[[32]]
[[32]]


***QUESTION 2***   

Let $a$ be a $(p x 1)$ vector. Use the definition of trace to show that the inner product $a^\intercal.a$ is equal to the trace
of the outer product $a.a^\intercal$.

In [41]:
# ANSWER & Example:

print(np.dot(a_transpose, a))
print(np.dot(a, a_transpose))

# We can see that the results are very different at this stage. 

[[14]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [40]:
# Calculating trace (sum of diagonal value)

print(np.dot(a_transpose, a).trace())
print(np.dot(a, a_transpose).trace())

14
14


***QUESTION 3***

Let $A$ be a square $(p x p)$ matrix and $c$ a scalar. Show that $tr(c.A) = c.tr(A)$.

In [44]:
A = np.matrix([
    [1,2],
    [3,4]
]
)

c = 5

print(np.dot(c, A).trace())
print(c*A.trace())

[[25]]
[[25]]


***QUESTION 4***  

Let $A$ be a square invertible $(p x p)$ matrix and $c \ne 0$ a scalar. Find the inverse of $(c.A)$.

In [51]:
A = np.matrix([
    [7, -2],
    [3, 5]
]
)

c = 5

c_A = np.dot(c, A)

print(np.linalg.inv(c_A)) # inverse of the multuplicative matrix

print(c*np.linalg.inv(A)) # inverse of the matrix multiplied by the scalar

# we can clearly see the difference between the two approaches.

[[ 0.02439024  0.0097561 ]
 [-0.01463415  0.03414634]]
[[ 0.6097561   0.24390244]
 [-0.36585366  0.85365854]]


***QUESTION 5***    

Let $A$ be a square $(2 ×2)$ matrix given by 

$
\quad A =
        \begin{pmatrix}
        a & b \\
        c & d \\
        \end{pmatrix}
$ 

Find the value for $f$ such that $B(f ) = \frac{1}{f}\begin{pmatrix} d & -b\\ -c & a\\ \end{pmatrix}$
gives the inverse of $A$. What condition should the matrix elements satisfy for the inverse to exist?

***QUESTION 6***   

Simplify the expression $(i^\intercal.i)$ and ${(i.i^\intercal)}^2$, where $i$ is the $(p × 1)$ unit vector.